// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnrhyijmmfmsuctyrxbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucmh5aWptbWZtc3VjdHlyeGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTIzMzgsImV4cCI6MjA2NDU4ODMzOH0.oGDqW6WINEWJE6De-XVyJfs2hFmjPOyjBH6wuW2ZyKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);